### ISSUE TITLE
AuthorizationBackend: Suppress stacktrace if user roles could not be filled

### ISSUE THREAD

**Issue by jochenkressin** [floragunncom/search-guard-authbackend-ldap#2]
Usecase (from customer):

Both internal user database and LDAP authentication and authorization is enabled.

When a user that is not present in LDAP (only internal user database) is authenticated, there's an error logged with stacktrace.

Source is LDAPAuthorizationBackend#fillRoles, lines 290ff:

```
            if (isValidDn(authenticatedUser)) {
                // assume dn
                if(log.isTraceEnabled()) {
                    log.trace("{} is a valid DN", authenticatedUser);
                }
                entry = LdapHelper.lookup(connection, authenticatedUser);

                if (entry == null) {
                    throw new ElasticsearchSecurityException("No user '" + authenticatedUser + "' found");
                }

            } else {
                
                entry = LDAPAuthenticationBackend.exists(user.getName(), connection, settings);
                
                if (entry == null) {
                    throw new ElasticsearchSecurityException("No user " + authenticatedUser + " found");
                }
            }
```

The LdapHelper.lookup and LDAPAuthenticationBackend.exists methods both throw LDAPExceptions (Runtime) in case the user cannot be found (LDAPHelper#lookup -> LDAPHelper#search -> SearchOperation#execute).

That's why the 

```
                if (entry == null) {
                    throw new ElasticsearchSecurityException("No user " + authenticatedUser + " found");
                }
```

is never reached and the catch-block is executed, l. 431 ff:

```
        catch (final Exception e) {
            log.error(e.toString(), e);
            throw new ElasticsearchSecurityException(e.toString(), e);
        }
```

Here we explicitely log an error with the stacktrace, which is not necessary IMHO.

Please also check AuthenticationBackend#authenticate, I think we have the same issue there.

**Comment by floragunn** [comment]
fixed with Version 5
