### ISSUE TITLE
LDAPS CA certificate

### ISSUE THREAD

**Issue by alesnav** [floragunncom/search-guard-authbackend-ldap#5]
Hello,

I think that it would be fine if there is one parameter which allows to specify the location of the CA certificate to connect to LDAP using LDAPS protocol.

Otherwise... how can we set it?

Thanks,
Best regards

**Comment by floragunn** [comment]
Currently the transport truststore is used for this

**Comment by alesnav** [comment]
So, LDAPS CA root and Elasticsearch CA root have to be the same one, right?

**Comment by floragunn** [comment]
It means that the certificate(chain) from your ldap server must be signed by one of the certificates in the transport truststore.

**Comment by alesnav** [comment]
Ah, understood. It does work fine and I think that it is not neccesary to add a new parameter in the configuration.

Maybe you should add this info in the LDAP docs (https://github.com/floragunncom/search-guard-docs/blob/master/ldap.md)

Thanks!
